openvfd: allow modprobe of openvfd.ko without param when there is no vfd.conf present

diff --git a/script/kernel/openvfd/files/openvfd b/script/kernel/openvfd/files/openvfd
--- a/script/kernel/openvfd/files/openvfd
+++ b/script/kernel/openvfd/files/openvfd
@@ -8,9 +8,9 @@ DriverLoaded() {
 
 }
 
-if [ -f "$USRCONFFILE" ]; then
+if ! DriverLoaded; then
 
-    if ! DriverLoaded; then
+    if [ -f "$USRCONFFILE" ]; then
 
         . "$USRCONFFILE"
 
@@ -28,26 +28,24 @@ vfd_display_type=${vfd_display_type}"
 
         echo "loading openvfd.ko with ${module_params}"
 
-        /sbin/modprobe openvfd ${module_params}
-
-    fi
-
-    if DriverLoaded; then
-
-        echo "starting OpenVFDService daemon"
-        /usr/bin/OpenVFDService ${clock_12h_format:+-12h}
-        exit 0
-
     else
 
-        echo "OpenVFDService daemon not started as loading openvfd.ko failed ..."
-        exit 1
+        module_params=""
+        echo "loading openvfd.ko"
 
     fi
+        /sbin/modprobe openvfd ${module_params}
+fi
+
+if DriverLoaded; then
+
+    echo "starting OpenVFDService daemon"
+    /usr/bin/OpenVFDService ${clock_12h_format:+-12h}
+    exit 0
 
 else
 
-    echo "ERROR: no /etc/openvfd/vfd.conf file found!"
+    echo "OpenVFDService daemon not started as loading openvfd.ko failed ..."
     exit 1
 
 fi
