Update init files

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
@@ -147,7 +147,13 @@ start() {
     # Mount themecache directory.
     if /usr/bin/test -n "${MM_THEMECACHE_URL}" && /usr/bin/test -z "${MM_MYTHTV_HOME_URL}" ; then
         /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Mounting ThemeCache from ${MM_THEMECACHE_URL}"
-        mm_url_mount "${MM_THEMECACHE_URL}" "/home/minimyth/.mythtv/cache/themecache"
+        if ! mm_url_mount "${MM_THEMECACHE_URL}" "/home/minimyth/.mythtv/cache/themecache" ; then
+            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Failed to mount ThemeCache from ${MM_THEMECACHE_URL}"
+            /bin/mkdir -p -m 777 "/home/minimyth/.mythtv/cache/themecache"
+            /bin/chmod 777 "/home/minimyth/.mythtv/cache/themecache"
+        else
+            /bin/chmod 777 "/home/minimyth/.mythtv/cache/themecache"
+        fi
     fi
 
     # Mount remotecache directory.
