init: improve handling error cases for external Theme and MenuTheme downloading

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/mythtv
@@ -134,50 +134,76 @@ start() {
     # Set the MythTV theme.
     if [ -n "${MM_THEME_NAME}" ] ; then
 
-        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Asking MythTV to use theme:${MM_THEME_NAME}"
-        mm_mythdb_settings_update "Theme" "${MM_THEME_NAME}"
+        if [ -n "${MM_THEME_URL}" ] ; then
 
-    fi
- 
-    # Try to mount MythTV theme directory.
-    if [ -n "${MM_THEME_URL}" ] ; then
+            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Trying to mount Theme from ${MM_THEME_URL} ..."
 
-        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Trying to mount theme from ${MM_THEME_URL}"
+            if ! mm_url_mount "${MM_THEME_URL}" "/usr/share/mythtv/themes/${MM_THEME_NAME}" ; then
 
-        if ! mm_url_mount "${MM_THEME_URL}" "/usr/share/mythtv/themes/${MM_THEME_NAME}" ; then
+                /usr/bin/logger -s -t minimyth -p "local0.err" "[init.d/mythtv] Can't download/mount theme from ${MM_THEME_URL}. Fallback to build-in ${DEFAULT_UI_THEME} ..."
+                mm_message_output info "Can't load Theme. Fall-back to build-in ${DEFAULT_UI_THEME} ..."
+                mm_mythdb_settings_update "Theme" "${DEFAULT_UI_THEME}"
+                sleep 5
 
-            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Can't download/mount theme from ${MM_THEME_URL}. Fallback to build-in ${DEFAULT_UI_THEME}..."
-            mm_message_output info "Can't load theme. Fall-back to build-in ${DEFAULT_UI_THEME} theme..."
-            mm_mythdb_settings_update "Theme" "${DEFAULT_UI_THEME}"
+            else
+
+                /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Theme from ${MM_THEME_URL} successfuly mounted! Setting to use ${MM_THEME_NAME} theme ..."
+                mm_mythdb_settings_update "Theme" "${MM_THEME_NAME}"
+
+            fi
 
         else
 
-            #mm_message_output info "selecting ${MM_THEME_NAME} theme ..."
-            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Theme from ${MM_THEME_URL} successfuly mounted..."
+            /usr/bin/logger -s -t minimyth -p "local0.err" "[init.d/mythtv] minimyth.conf sets theme to ${MM_THEME_NAME} but no MM_THEME_URL is provided! Fallback to build-in ${DEFAULT_UI_THEME} ..."
+            mm_message_output info "No Theme URL is set! Fall-back to build-in ${DEFAULT_UI_THEME} ..."
+            mm_mythdb_settings_update "Theme" "${DEFAULT_UI_THEME}"
+            sleep 5
+
         fi
+
+    else
+
+        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] MythTV will use build-in ${DEFAULT_UI_THEME} theme ..."
+        mm_mythdb_settings_update "Theme" "${DEFAULT_UI_THEME}"
+
     fi
 
     # Set the MythTV theme menu.
     if [ -n "${MM_THEMEMENU_NAME}" ] ; then
 
-        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Forcing MenuTheme ${MM_THEME_NAME} from config file..."
-        mm_mythdb_settings_update "MenuTheme" "${MM_THEMEMENU_NAME}"
+        if [ -n "${MM_THEMEMENU_URL}" ] ; then
 
-    fi
- 
-    # Mount MythTV Menu directory.
-    if [ -n "${MM_THEMEMENU_URL}" ] ; then
+            /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Trying to mount MenuTheme from ${MM_THEMEMENU_URL} ..."
 
-        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] Mounting MenuTheme from ${MM_THEMEMENU_URL}"
+            if ! mm_url_mount "${MM_THEMEMENU_URL}" "/usr/share/mythtv/themes/${MM_THEMEMENU_NAME}" ; then
 
-        if ! mm_url_mount "${MM_THEMEMENU_URL}" "/usr/share/mythtv/themes/${MM_THEMEMENU_NAME}" ; then
+                /usr/bin/logger -s -t minimyth -p "local0.err" "[init.d/mythtv] Can't download/mount MenuTheme from ${MM_THEMEMENU_URL}. Fallback to build-in ${DEFAULT_MENUTHEME} ..."
+                mm_message_output info "Can't load MenuTheme. Fall-back to build-in ${DEFAULT_MENUTHEME} ..."
+                mm_mythdb_settings_update "MenuTheme" "${DEFAULT_MENUTHEME}"
+                sleep 5
 
-            mm_message_output err "error: mount of 'MM_THEMEMENU_URL=${MM_THEMEMENU_URL}' failed."
-            return 1
+            else
+
+                /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] MenuTheme from ${MM_THEMEMENU_URL} successfuly mounted! Setting to use ${MM_THEMEMENU_NAME} MenuTheme.."
+                mm_mythdb_settings_update "MenuTheme" "${MM_THEMEMENU_NAME}"
+
+            fi
+
+        else
+
+            /usr/bin/logger -s -t minimyth -p "local0.err" "[init.d/mythtv] minimyth.conf sets MenuTheme to MM_THEMEMENU_NAME but no ${MM_THEMEMENU_URL} is provided. Fallback to build-in ${DEFAULT_MENUTHEME} ..."
+            mm_message_output info "No MenuTheme URL is set! Fall-back to build-in ${DEFAULT_MENUTHEME} ..."
+            mm_mythdb_settings_update "MenuTheme" "${DEFAULT_MENUTHEME}"
+            sleep 5
 
         fi
-    fi
 
+    else
+
+        /usr/bin/logger -s -t minimyth -p "local0.info" "[init.d/mythtv] MythTV will use build-in ${DEFAULT_MENUTHEME} MenuTheme ..."
+        mm_mythdb_settings_update "MenuTheme" "${DEFAULT_MENUTHEME}"
+
+    fi
 
     # Mount remotecache directory.
     if [ -n "${MM_REMOTECACHE_URL}" ] && [ -z "${MM_MYTHTV_HOME_URL}" ] ; then
