doc: update changelog

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/conf.d/S_MYTHTV b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/conf.d/S_MYTHTV
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/conf.d/S_MYTHTV
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/init.d/conf.d/S_MYTHTV
@@ -62,6 +62,7 @@ conf_write_S_MYTHTV() {
   conf_variable_write "${conf_file}" MM_REMOTECACHE_URL        "${MM_REMOTECACHE_URL}"
   conf_variable_write "${conf_file}" MM_MYTHTV_DRAW_ON         "${MM_MYTHTV_DRAW_ON}"
   conf_variable_write "${conf_file}" MM_MYTHTV_DRM_VIDEO       "${MM_MYTHTV_DRM_VIDEO}"
+  conf_variable_write "${conf_file}" MM_MYTHTV_EGLFS_CONFIG    "${MM_MYTHTV_EGLFS_CONFIG}"
   conf_variable_write "${conf_file}" MM_MYTHTV_SET_ENV_VAR     "${MM_MYTHTV_SET_ENV_VAR}"
 
   # Moved from P_MAKEMKV as this variable is needed for enabling/disabling
@@ -76,6 +77,23 @@ conf_write_S_MYTHTV() {
       exit 1
     fi
     /bin/chmod 0400 /home/minimyth/.mythtv/RAOPKey.rsa
+  fi
+
+  if [ ! -z "x${MM_MYTHTV_EGLFS_CONFIG}" ] && [ "x${MM_MYTHTV_DRAW_ON}" = "xeglfs" ]; then
+    /bin/rm -f /home/minimyth/.mythtv/eglfs-config.json
+    if [ "${MM_MYTHTV_EGLFS_CONFIG}" = "card0" ] ; then
+      echo "{ \"device\": \"/dev/dri/card0\" }" > /home/minimyth/.mythtv/eglfs-config.json
+    elif [ "${MM_MYTHTV_EGLFS_CONFIG}" = "card1" ] ; then
+      echo "{ \"device\": \"/dev/dri/card1\" }" > /home/minimyth/.mythtv/eglfs-config.json
+    elif [ "${MM_MYTHTV_EGLFS_CONFIG}" = "custom" ] ; then
+      mm_confro_get eglfs-config.json /home/minimyth/.mythtv/eglfs-config.json
+      if [ ! -e /home/minimyth/.mythtv/eglfs-config.json ] ; then
+        mm_message_output err "error: failed to fetch 'eglfs-config.json' file."
+        exit 1
+      fi
+    else
+      mm_message_output err "error: wrong value was set for MM_MYTHTV_EGLFS_CONFIG."
+    fi
   fi
 
   if [ "x${MM_WUNDERGROUND_KEY}" = "xyes" ] ; then
