install-on-emmc: add capability to erase and install only bootloader

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
@@ -1,12 +1,21 @@
 #!/bin/sh
 
-# Script:
-#  1.duplicates first rootfs_sise MBytes from SD card to eMMC
-#  2.duplicates bootloader from SD card to eMMC
+# Script works in 3 commands:
+#  Mode1: when called with 'install' command:
+#    1.duplicates first rootfs_sise MBytes from SD card to eMMC
+#    2.duplicates bootloader from SD card to eMMC (Allwinner) or updates extlinux.conf (other platforms)
+#  Mode2: when called with 'erase' command:
+#    1. Erase eMMC by writing zero to first 'erase_areas_size' MBytes of eMMC
+#  Mode3: when called with 'bootloader' command:
+#    1. Duplicates bootloader from SD card to eMMC (Allwinner) or updates extlinux.conf (other platforms)
+#
 #
 # safety_margina is mount of extra size beyond 1st + 2nd + 3rd partitions to be
 # duplicated from SD card to eMMC. In MBytes
 safety_margin=100
+#
+# area at emmc begininng filled with zero to make emmc erased. In MBytes.
+erase_areas_size=1024
 
 #-----------------------------
 
@@ -51,7 +60,9 @@ safety_margin=100
 
 
 
-ver=1.0
+ver=1.1
+
+command=$1
 
 confirm() {
 
@@ -67,6 +78,17 @@ confirm() {
     else
         echo "Exiting stript (by user no-confirm)"
         exit 0
+    fi
+}
+
+is_booted_from_emmc() {
+    if [ "${sdcard_dev}" = "${emmc_dev}" ]; then
+        echo " "
+        echo " "
+        echo "Your device is currently booted from the eMMC so can't install from eMMC to eMMC ;-p. Exiting ..."
+        echo " "
+        echo " "
+        exit 1
     fi
 }
 
@@ -158,16 +180,19 @@ update_emmc_bootloader_config() {
     fi
 }
 
+erase_emmc() {
+    dd if=/dev/zero of=/dev/${emmc_dev} bs=1M count=${erase_areas_size} conv=fsync
+}
+
 write_to_emmc_bootloader() {
 
     if [ $platform_type = 1 ] ; then
         # this is for allwinner
-        echo "  ==> copying bootloader from ${sdcard_dev} to ${emmc_dev} ..."
+        echo "  ==> erasing old bootloader ..."
         echo 0 > /sys/block/${emmc_dev}boot0/force_ro
-        echo "  ==> erasing existing bootloader ..."
         dd if=/dev/zero of=/dev/${emmc_dev}boot0 bs=1k count=2048 conv=fsync
         dd if=/dev/zero of=/dev/${emmc_dev} bs=1k count=2048 conv=fsync
-        echo "  ==> copying bootloader ..."
+        echo "  ==> copying bootloader from ${sdcard_dev} to ${emmc_dev} ..."
         dd if=/dev/${sdcard_dev} of=/dev/${emmc_dev}boot0 bs=1k count=2048 conv=fsync
         dd if=/dev/${sdcard_dev} of=/dev/${emmc_dev} bs=1k count=2048 conv=fsync
         echo "bootloader copied to eMMC ..."
@@ -239,11 +264,6 @@ if [ -z "${emmc_dev}" ]; then
   exit 1
 fi
 
-if [ "${sdcard_dev}" = "${emmc_dev}" ]; then
-  echo "Your device is booted from the eMMC! Exiting ..."
-  exit 1
-fi
-
 if [ $platform_type = 5 ] ; then
     get_size_to_copy 6
 else
@@ -253,22 +273,61 @@ fi
 echo " "
 echo "System booted from : ${sdcard_dev}"
 echo "eMMC device        : ${emmc_dev}"
-echo "SDcard usage       : ${storage_usage}MB"
 
-confirm "to copy ${storage_usage}MB from SD card to eMMC"
+if [[ "${command}" =~ "erase" ]] ; then
+    echo " "
+    echo "erasing eMMC ..."
 
-confirm "You ARE SURE to OVERWRITE eMMC content"
+    confirm "to erase eMMC"
+    confirm "You ARE SURE to erase eMMC content"
 
-echo "copying of ${storage_usage}MB from SD card to eMMC ..."
-duplicate_sdcard_to_emmc $((${storage_usage} + $safety_margin))
-echo "copying to eMMC done ..."
+    erase_emmc
 
-echo "copying bootloader to eMMC ..."
-confirm "to install bootloader on eMMC"
-write_to_emmc_bootloader
+    echo " "
+    echo "Done ..."
+    echo " "
+    exit 0
 
-echo " "
-echo "Now you can remove SD card and reboot ..."
-echo " "
+elif [[ "${command}" =~ "bootloader" ]] ; then
+    is_booted_from_emmc
+
+    echo " "
+    echo "copying bootloader to eMMC ..."
+
+    confirm "to install bootloader on eMMC"
+
+    write_to_emmc_bootloader
+
+    echo " "
+    echo "Done ..."
+    echo " "
+    exit 0
+
+elif [[ "${command}" =~ "install" ]] ; then
+    is_booted_from_emmc
+
+    echo "SDcard usage       : ${storage_usage}MB"
+
+    confirm "to copy ${storage_usage}MB from SD card to eMMC"
+
+    confirm "You ARE SURE to OVERWRITE eMMC content"
+
+    echo "copying of ${storage_usage}MB from SD card to eMMC ..."
+    duplicate_sdcard_to_emmc $((${storage_usage} + $safety_margin))
+    echo "copying to eMMC done ..."
+
+    echo "copying bootloader to eMMC ..."
+    confirm "to install bootloader on eMMC"
+    write_to_emmc_bootloader
+
+    echo " "
+    echo "Now you can remove SD card and reboot ..."
+    echo " "
+else
+    echo " "
+    echo "Run script with command: erase|bootloader|install"
+    echo " "
+    exit 0
+fi
 
 exit 0
