install-on-emmc: stop checking for errors on partprobe as it returns error in i.e. swap aprtition on device is already mounted

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
@@ -86,9 +86,14 @@ error() {
 
 do_cmd() {
     log "Executing $*"
-    $* 2>>${log_file}
-    if [ $? -ne 0 ] ; then
-        error "Executing $* failed ..."
+    #for partprobe stop checking for errors...
+    if [[ "$*" =~ "partprobe" ]] ; then
+        $* 2>>${log_file}
+    else
+        $* 2>>${log_file}
+        if [ $? -ne 0 ] ; then
+            error "Executing $* failed ..."
+        fi
     fi
 }
 
