install-on-emmc: fix script exit on erase command when systems is without sd card.

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
@@ -85,7 +85,7 @@ is_booted_from_emmc() {
     if [ "${sdcard_dev}" = "${emmc_dev}" ]; then
         echo " "
         echo " "
-        echo "Your device is currently booted from the eMMC so can't install from eMMC to eMMC ;-p. Exiting ..."
+        echo "Your device is currently booted from the eMMC so nstall from eMMC to eMMC not make much sense. Exiting ..."
         echo " "
         echo " "
         exit 1
@@ -284,10 +284,6 @@ if [ -z "${emmc_dev}" ]; then
   exit 1
 fi
 
-if [ -z "${sdcard_dev}" ]; then
-  echo "Can't determine SDcard  device! Exiting ..."
-  exit 1
-fi
 
 get_size_to_copy
 
@@ -315,6 +311,11 @@ if [[ "${command}" =~ "erase" ]] ; then
 elif [[ "${command}" =~ "bootloader" ]] ; then
     is_booted_from_emmc
 
+    if [ -z "${sdcard_dev}" ]; then
+        echo "Can't determine SDcard  device! Exiting ..."
+        exit 1
+    fi
+
     echo " "
     echo "copying bootloader to eMMC ..."
 
@@ -330,6 +331,11 @@ elif [[ "${command}" =~ "bootloader" ]] ; then
 elif [[ "${command}" =~ "install" ]] ; then
     is_booted_from_emmc
 
+    if [ -z "${sdcard_dev}" ]; then
+        echo "Can't determine SDcard  device! Exiting ..."
+        exit 1
+    fi
+
     confirm "to copy ${storage_usage}MB from SD card to eMMC"
 
     confirm "You ARE SURE to OVERWRITE eMMC content"
@@ -343,7 +349,7 @@ elif [[ "${command}" =~ "install" ]] ; then
     write_to_emmc_bootloader
 
     echo " "
-    echo "Now you can remove SD card and reboot ..."
+    echo "System was successfuly installed on eMMC ..."
     echo " "
 else
     echo " "
