install-on-emmc: cosmetics on erro message on systems without emmc

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/install-on-emmc
@@ -274,15 +274,11 @@ echo " "
 what_platform
 # mark anything above 8 (amlogic, rpi) as unsupported (yet)
 if [ $platform_type -gt 8 ] ; then
+  echo " "
   echo "Unsupported (yet) platform! Exiting ..."
+  echo " "
   exit 1
 fi
-
-if [ x"${emmc_dev}" = "xN/A" ]; then
-  echo "Can't determine eMMC device! Exiting ..."
-  exit 1
-fi
-
 
 get_size_to_copy
 
@@ -292,6 +288,13 @@ echo "SD card device       : ${sdcard_dev}"
 echo "eMMC device          : ${emmc_dev}"
 echo "Boot device has      : ${part_no} partitions"
 echo "Boot device usage    : ${storage_usage}MB"
+
+if [ x"${emmc_dev}" = "xN/A" ]; then
+  echo " "
+  echo "Can't determine eMMC device! Exiting ..."
+  echo " "
+  exit 1
+fi
 
 if [[ "${command}" =~ "erase" ]] ; then
     echo " "
