Add OSD notifications about new on-line mm2 version avaliability

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
@@ -65,8 +65,39 @@ $2 \
 
 }
 
+rm -f ${log_file}
 
-if [ "x${command}" = "xdoupdate" ] ; then
+if [ "x${command}" = "xcheck_new_version" ] ; then
+
+    dry_run="--dry-run"
+
+    run_rsync "${MM_MINIMYTH_ONLINE_UPDATES_URL}/version" "/etc/version" ${dry_run}
+
+    is_error=`cat ${log_file} | grep -c "error"`
+
+    if [ ${is_error} -eq 0 ] ; then
+
+        number_upd_files=`cat ${log_file} | grep "Number of regular files transferred" | cut -d" " -f9 | sed -e 's/,//g'`
+
+        if [ x${files_total} = "x0" ] ; then
+
+            echo "SystemIsAlreadyUpToDate"
+            exit 0
+
+        else
+
+            echo "NewVersionIsAvaliable"
+            exit 0
+
+        fi
+
+    else
+
+        echo 'Error contacting updates server !'
+        exit 1
+    fi
+
+elif [ "x${command}" = "xdoupdate" ] ; then
 
     echo 'Starting on-line update ...'
     dry_run="--delete"
@@ -78,7 +109,6 @@ else
 
 fi
 
-rm -f ${log_file}
 
 run_rsync "${MM_MINIMYTH_ONLINE_UPDATES_URL}/boot/dtbs/"      "/media/boot/dtbs"  ${dry_run}
 run_rsync "${MM_MINIMYTH_ONLINE_UPDATES_URL}/boot/*Image"     "/media/boot"       ${dry_run}
diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_notify_updates b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_notify_updates
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_notify_updates
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_notify_updates
@@ -1,19 +1,26 @@
 #!/bin/sh
 
-ssh_command="/usr/bin/ssh -c aes128-ctr root@@MM_MASTER_SERVER@"
+ssh_command="/usr/bin/ssh -c aes128-ctr root@192.168.1.254"
 
 pids=`/bin/pidof mm_notify_updates`
 instances=`/bin/echo ${pids} | /usr/bin/wc -w`
 if [ ${instances} -ne 1 ] ; then
+    echo "Another instance is running ... Exiting with rc=1"
     exit 1
 fi
 
 . /etc/rc.d/functions
 . /etc/mm_ui_localizations_sh
 
+check_period=$1
+
 trap "_exit_" 0 1 2 3 15
 
-check_period=$1
+if [ x${check_period} = "x0" ] || [ x${check_period} = "xno" ] || [ x${check_period} = "x" ]; then
+    echo "Check period not speciffied or = 0 or set to \'no\'. Exiting with rc=0"
+    exit 0
+fi
+
 check_period=$((${check_period} * 60))
 
 _exit_()
@@ -28,23 +35,45 @@ _exit_()
     done
 }
 
-/bin/sleep 900
+#/bin/sleep 900
 
-/usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] MM_NOTIFY_UPDATES now checks for updates every ${check_period} sec..."
+/usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] will check for updates every ${check_period} sec..."
 
-while true ; do
-  ${ssh_command} pacman -Sy > /dev/null 2>&1
-  updates_list=`${ssh_command} pacman -Qqu 2> /dev/null`
-  if [ -n ${updates_list} ] ; then
-    packages=`/bin/echo ${updates_list} | /usr/bin/wc -w`
-    if [ ! ${packages} = 0 ] ; then
-      /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] ${packages} updated packages were detected..."
-      mm_show_mythnotify "${updates_detected_str}" "There is ${packages} updated package(s)..." 'warning' '12'
-    else
-      /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] No updated packages were detected..."
-    fi
-  fi
-  /bin/sleep ${check_period}
-done
+if [ "x${MM_MINIMYTH_ONLINE_UPDATES_URL}" = "xlocal" ] ; then
+    # case for PXE booted system
+    while true ; do
+        ${ssh_command} pacman -Sy > /dev/null 2>&1
+        updates_list=`${ssh_command} pacman -Qqu 2> /dev/null`
+        if [ -n ${updates_list} ] ; then
+            packages=`/bin/echo ${updates_list} | /usr/bin/wc -w`
+            if [ ! ${packages} = 0 ] ; then
+                /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] ${packages} updated packages were detected..."
+                mm_show_mythnotify "${updates_detected_str}" "There is ${packages} updated package(s)..." 'warning' '12'
+            else
+                /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] No updated packages were detected..."
+            fi
+        fi
+        /bin/sleep ${check_period}
+    done
+elif [ ! "x${MM_MINIMYTH_ONLINE_UPDATES_URL}" = "x" ] ; then
+    # case for SD card booted system
+    while true ; do
+        are_updates_aval=`mm_do_online_update check_new_version`
+        if [ $? -eq 0 ] ; then
+            if [ `echo ${are_updates_aval} | grep -c "NewVersionIsAvaliable"` -gt 0 ] ; then
+                /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] ${MM_MINIMYTH_ONLINE_UPDATES_URL} reports system updates ..."
+                mm_show_mythnotify "${updates_detected_str}" "New version of MiniMyth2 is avaliable ..." 'warning' '12'
+            else
+                /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] No updates at ${MM_MINIMYTH_ONLINE_UPDATES_URL} ..."
+            fi
+        else
+            /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] Error contacting ${MM_MINIMYTH_ONLINE_UPDATES_URL}. Exiting with rc=1 ..."
+            exit 1
+        fi
+        /bin/sleep ${check_period}
+    done
 
-exit 0
+else
+    /usr/bin/logger -t minimyth -p "local0.info" "[mm_notify_updates] No MM_MINIMYTH_ONLINE_UPDATES_URL is set. Exiting with rc=0 ..."
+    exit 0
+fi
