install-on-emmc: add capability of local (nfs) and ota bootloader updates

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/mm_do_online_update
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# v2021.02.24
+# v2026.08.24
 
 . /etc/rc.d/functions
 . /etc/mm_ui_localizations_sh
@@ -110,6 +110,22 @@ elif [ "x${command}" = "xdoupdate" ] ; then
 
     echo 'Starting on-line update ...'
     dry_run="--delete"
+
+elif [ "x${command}" = "xgetbootloaders" ] ; then
+
+    echo 'Starting downloading bootloaders ...'
+    dry_run="--delete"
+
+    bootloaders_dir="/tmp/bootloaders/"
+    mkdir -p ${bootloaders_dir}
+
+    run_rsync "${MM_MINIMYTH_ONLINE_UPDATES_URL}/bootloaders.tar.bz2" "${bootloaders_dir}" ${dry_run}
+    if [ `check_log_for_errors` -eq 0 ] ; then
+        exit 0
+    else
+        echo 'Error contacting updates server !'
+        exit 1
+    fi
 
 else
 
