test-fans: some improvements

diff --git a/script/meta/minimyth/files/source/rootfs/usr/bin/test-fans b/script/meta/minimyth/files/source/rootfs/usr/bin/test-fans
--- a/script/meta/minimyth/files/source/rootfs/usr/bin/test-fans
+++ b/script/meta/minimyth/files/source/rootfs/usr/bin/test-fans
@@ -2,7 +2,12 @@
 
 fan_speeds="32 64 128 192 255 192 128 64 32 0"
 
-sysfs_fan=`find /sys/devices/platform/*/hwmon -name pwm[0-9]`
+sysfs_fan=`find /sys/devices/platform/*/hwmon -name pwm[0-9] 2>/dev/null`
+
+if [ x${sysfs_fan} = "x" ] ; then
+    echo "Can't find any fan in your's system! Exiting ..."
+    exit 1
+fi
 
 while true ; do
     for fan in ${sysfs_fan} ; do 
