Add better loging of curl failed http download/uploads

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
@@ -106,7 +106,7 @@ mm_url_conf_get() {
 
     /usr/bin/logger -s -t minimyth -p "local0.error" \
         "function 'mm_url_conf_get' is no longer supported. use 'mm_url_confro_get' or 'mm_url_confrw_get' instead."
-
+#"
     /bin/false
     return
 }
@@ -231,9 +231,12 @@ mm_url_http_get() {
     /usr/bin/test -n "${LOCAL_DIR}" && /bin/mkdir -p "${LOCAL_DIR}"
     /usr/bin/test -n "${LOCAL_DIR}" && /usr/bin/test ! -d "${LOCAL_DIR}" && return
 
-    /usr/bin/curl -s -f "http://${REMOTE_SERVER}${REMOTE_FILE}" -o "${LOCAL_FILE}" || return
-
-    /usr/bin/logger -s -t minimyth -p "local0.info" "'http://${REMOTE_SERVER}${REMOTE_FILE}' downloaded."
+    rc=`/usr/bin/curl -s -S -f "http://${REMOTE_SERVER}${REMOTE_FILE}" -o "${LOCAL_FILE}" 2>&1`
+    if [ $? -ne 0 ] ; then
+        /usr/bin/logger -s -t minimyth -p "local0.info" "Download from 'http://${REMOTE_SERVER}${REMOTE_FILE}' returns: '${rc}'"
+    else
+        /usr/bin/logger -s -t minimyth -p "local0.info" "'http://${REMOTE_SERVER}${REMOTE_FILE}' downloaded..."
+    fi
 
     return
 }
@@ -375,7 +378,7 @@ mm_url_conf_put() {
     local REMOTE_FILE=$2
 
     /usr/bin/logger -s -t minimyth -p "local0.error" \
-        "function 'mm_url_conf_put' is no longer supported. use 'mm_url_confrw_put' instead."
+        "'mm_url_conf_put' is no longer supported. use 'mm_url_confrw_put' instead."
 
     /bin/false
     return
@@ -468,21 +471,21 @@ mm_url_http_put() {
 
     if [ ! -f "${LOCAL_FILE}" ] ; then
         /usr/bin/logger -s -t minimyth -p "local0.error"  \
-            "[functions/mm_url_http_put] cannot post conf file '${LOCAL_FILE}' because file not found."
+            "[functs/mm_url_http_put] cannot post conf file '${LOCAL_FILE}' because file not found."
         /bin/false
         return
     fi
 
-    if /usr/bin/curl -s -f -T "${LOCAL_FILE}" "http://${REMOTE_SERVER}${REMOTE_FILE}" ; then
-        /usr/bin/logger -s -t minimyth -p "local0.info"  \
-            "[functions/mm_url_http_put] 'http://${REMOTE_SERVER}${REMOTE_FILE}' posted."
-        /bin/true
+    rc=`/usr/bin/curl -s -S -f -T "${LOCAL_FILE}" "http://${REMOTE_SERVER}${REMOTE_FILE}" 2>&1`
+    if [ $? -ne 0 ] ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "Uploading to 'http://${REMOTE_SERVER}${REMOTE_FILE}' failed with error: ${rc}"
+        /bin/false
         return
     else
-        /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_url_http_put] 'http://${REMOTE_SERVER}${REMOTE_FILE}' failed to post. Will retry with verbose. For output, look on /var/log/minimyth.err"
-            /usr/bin/curl -v -S -T "${LOCAL_FILE}" "http://${REMOTE_SERVER}${REMOTE_FILE}" > /var/log/minimyth.err 2>&1
-        /bin/false
+        /usr/bin/logger -s -t minimyth -p "local0.info" \
+            "[functs/mm_url_http_put] 'http://${REMOTE_SERVER}${REMOTE_FILE}' uploaded..."
+        /bin/true
         return
     fi
 
@@ -588,7 +591,7 @@ mm_conf_get() {
     local LOCAL_FILE=$2
 
     /usr/bin/logger -s -t minimyth -p "local0.error" \
-        "function 'mm_conf_get' is no longer supported. use 'mm_confro_get' or 'mm_confrw_get' instead."
+        "'mm_conf_get' is no longer supported. use 'mm_confro_get' or 'mm_confrw_get' instead."
 
     /bin/false
     return
@@ -617,7 +620,7 @@ mm_conf_put() {
     local LOCAL_FILE=$2
 
     /usr/bin/logger -s -t minimyth -p "local0.error" \
-        "function 'mm_conf_put' is no longer supported. use 'mm_confrw_put' instead."
+        "'mm_conf_put' is no longer supported. use 'mm_confrw_put' instead."
 
     /bin/false
     return
@@ -862,13 +865,13 @@ mm_themecache_save() {
 
     if [ ! -d /home/minimyth/.mythtv/cache/themecache ] ; then
         /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_themecache_save] failed to create the MythTV themecache file because the MythTV themecache directory does not exist!"
+            "[functs/mm_themecache_save] failed to create the MythTV themecache file because the MythTV themecache directory does not exist!"
         /bin/false
         return
     fi
     if [ -z "`cd /home/minimyth/.mythtv/cache/themecache ; /bin/ls -A`" ] ; then
         /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_themecache_save] failed to create the MythTV themecache file because the MythTV themecache directory seems to be empty!"
+            "[functs/mm_themecache_save] failed to create the MythTV themecache file because the MythTV themecache directory seems to be empty!"
         /bin/false
         return
     fi
@@ -890,7 +893,7 @@ mm_themecache_save() {
     if [ $? -ne 0 ] ; then
         /bin/rm -f ${LOCAL_FILE}
         /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_themecache_save] failed to create the MythTV themecache file because squashfs failed."
+            "[functs/mm_themecache_save] failed to create the MythTV themecache file because squashfs failed."
         /bin/false
         return
     fi
@@ -901,7 +904,7 @@ mm_themecache_save() {
     if [ $? -ne 0 ] ; then
         /bin/rm -f ${LOCAL_FILE}
         /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_themecache_save] failed to upload the MythTV themecache file!"
+            "[functs/mm_themecache_save] failed to upload the MythTV themecache file!"
         /bin/false
         return
     fi
@@ -916,7 +919,7 @@ mm_cookiejar_save() {
         mm_confrw_put "mythbrowser_cookiejar.txt" "/home/minimyth/.mythtv/MythBrowser/cookiejar.txt"
         if [ $? -ne 0 ] ; then
             /usr/bin/logger -s -t minimyth -p "local0.error" \
-                "[functions/mm_cookiejar_save] failed to upload the MythBrowser cookiejar.txt file!"
+                "[functs/mm_cookiejar_save] failed to upload the MythBrowser cookiejar.txt file!"
             /bin/false
             return
         fi
@@ -929,7 +932,7 @@ mm_cookiejar_save() {
         rm -f /tmp/google-chrome-config.tar.bz2
         if [ $? -ne 0 ] ; then
             /usr/bin/logger -s -t minimyth -p "local0.error" \
-                "[functions/mm_cookiejar_save] failed to upload the google-chrome-config.tar.bz2 file!"
+                "[functs/mm_cookiejar_save] failed to upload the google-chrome-config.tar.bz2 file!"
             /bin/false
             return
         fi
@@ -942,14 +945,14 @@ mm_cookiejar_save() {
         rm -f /tmp/mozilla-firefox-config.tar.bz2
         if [ $? -ne 0 ] ; then
             /usr/bin/logger -s -t minimyth -p "local0.error" \
-                "[functions/mm_cookiejar_save] failed to upload the mozilla-firefox-config.tar.bz2 file!"
+                "[functs/mm_cookiejar_save] failed to upload the mozilla-firefox-config.tar.bz2 file!"
             /bin/false
             return
         fi
     fi
 
     /usr/bin/logger -s -t minimyth -p "local0.error" \
-        "[functions/mm_cookiejar_save] MythBrowser cookiejar.txt file and Chrome/Mozilla configs uploaded sucessfuly..."
+        "[functs/mm_cookiejar_save] MythBrowser cookiejar.txt file and Chrome/Mozilla configs uploaded sucessfuly..."
     /bin/true
     return
 }
@@ -1674,13 +1677,13 @@ mm_mythdb_settings_get() {
 
 
 #===============================================================================
-# Hardware processing functions.
+# Hardware processing functs.
 #===============================================================================
 
 #-------------------------------------------------------------------------------
 #-------------------------------------------------------------------------------
 mm_hardware_cpu_process() {
-    local cpu_process_function=$1
+    local cpu_process_funct=$1
 
     local vendor
     local family
@@ -1692,7 +1695,7 @@ mm_hardware_cpu_process() {
     family=`/bin/grep '^cpu family[[:cntrl:]]*:' /proc/cpuinfo | /usr/bin/head -n1 | /usr/bin/awk -F ": " '{ print $2 }'`
     model=` /bin/grep '^model[[:cntrl:]]*:'      /proc/cpuinfo | /usr/bin/head -n1 | /usr/bin/awk -F ": " '{ print $2 }'`
 
-    /bin/echo `${cpu_process_function} ${vendor} ${family} ${model}` | mm_uniq
+    /bin/echo `${cpu_process_funct} ${vendor} ${family} ${model}` | mm_uniq
 }
 
 mm_hardware_cpu2kernel_map() {
@@ -1924,11 +1927,11 @@ mm_x_start() {
             i=${timeout}
         else
             if [ $i -eq ${timeout} ] ; then
-                /usr/bin/logger -t minimyth -p "local0.err" "[functions/mm_x_start] Timeout waiting for finishing following sequential init scripts: \"${in_progress}\""
+                /usr/bin/logger -t minimyth -p "local0.err" "[functs/mm_x_start] Timeout waiting for finishing following sequential init scripts: \"${in_progress}\""
                 /bin/false
                 return
             else
-                /usr/bin/logger -t minimyth -p "local0.info" "[functions/mm_x_start] Still waiting to finish sequential init scripts. Remains:\"${in_progress}\""
+                /usr/bin/logger -t minimyth -p "local0.info" "[functs/mm_x_start] Still waiting to finish sequential init scripts. Remains:\"${in_progress}\""
                 /bin/sleep 1
             fi
         fi
@@ -2336,7 +2339,7 @@ mm_reload_voip_config() {
             mm_confro_get sip-daemon.conf /etc/sip-daemon.conf
             if [ ! -e /etc/sip-daemon.conf ] ; then
                 /usr/bin/logger -s -t minimyth -p "local0.error" \
-                    "[functions/mm_reload_voip_config] failed to load sip-daemon.conf file..."
+                    "[functs/mm_reload_voip_config] failed to load sip-daemon.conf file..."
                 /bin/false
                 return
             fi
@@ -2345,12 +2348,12 @@ mm_reload_voip_config() {
         mm_confro_get phone-book.xml /home/minimyth/.mythtv/phone.xml
         if [ ! -e /home/minimyth/.mythtv/phone.xml ] ; then
             /usr/bin/logger -s -t minimyth -p "local0.error" \
-                "[functions/mm_reload_voip_config] failed to load phone-book.xml file..."
+                "[functs/mm_reload_voip_config] failed to load phone-book.xml file..."
             /bin/false
             return
         fi
         /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_reload_voip_config] restarting sip-daemon.py..."
+            "[functs/mm_reload_voip_config] restarting sip-daemon.py..."
         /bin/touch /tmp/exit.sem
         /bin/sleep 3
         /usr/bin/sip-daemon.sh &
