functions/kodi.sh: add simple capability of save/resore kodi settings in conf-rw at kodi.sh starting/exiting

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
@@ -1018,6 +1018,7 @@ mm_cookiejar_save() {
     return
 }
 
+
 mm_mythbrowser_cookies_restore() {
 
     /bin/rm -f /home/minimyth/.mythtv/MythBrowser/cookiejar.txt
@@ -1078,6 +1079,53 @@ mm_bt_state_restore() {
     /bin/true
     return
 }
+
+
+mm_kodi_settings_save() {
+
+    local filename="kodi-settings.tar.bz2"
+
+    if [ -d /home/minimyth/.kodi ] ; then
+        cd /home/minimyth
+        tar -jcf /tmp/${filename} ./.kodi*
+        mm_confrw_put "${filename}" "/tmp/${filename}"
+        rm -f /tmp/${filename}
+        if [ $? -ne 0 ] ; then
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
+                "[functions/mm_cookiejar_save] failed to upload the ${filename} file!"
+            /bin/false
+            return
+        fi
+    fi
+
+    /usr/bin/logger -s -t minimyth -p "local0.info" \
+        "[functions/mm_kodi_settings_save] Kodi settings uploaded sucessfuly ..."
+    /bin/true
+    return
+}
+
+
+mm_kodi_settings_restore() {
+
+    local filename="kodi-settings.tar.bz2"
+
+    mm_confrw_get "${filename}" "/tmp/${filename}"
+    if [ $? -ne 0 ] ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "[functions/mm_kodi_settings_restore] failed to get ${filename} file ..."
+        /bin/false
+        return
+    fi
+    /bin/rm -rf /home/minimyth/.kodi*
+    bunzip2 -dc /tmp/${filename} | tar -xf - -C /home/minimyth/
+    rm -f /tmp/${filename}
+
+    /usr/bin/logger -s -t minimyth -p "local0.info" \
+        "[functions/mm_kodi_settings_restore] state restored sucessfuly ..."
+    /bin/true
+    return
+}
+
 
 mm_message_output() {
     local LEVEL=$1
