mm2: add bluetooth audio support
This adds bt audio support in MiniMyth2.

Now, when bt audio headset is paired with mm2,
-power-on of bt headset will automatically switching audio output to bt headset
-power-off of bt headset will automatically switching audio output back to default (hdmi when mm2 autodiscovers hw)
-standby/sleep/mythfrontend_restart will revert audio output to default

Before bt audio usage, bt headset needs to be paired with mm2.
This can be done with classicall Linux bt cli pairing proceudure
(best probably with help of bluetoothctl used in telnet session to mm2)

enjoy :-)

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
@@ -136,6 +136,7 @@ mm_url_confro_get() {
     local HOST_NAME
     local REMOTE_FILE_0
     local REMOTE_FILE_1
+    local REMOTE_FILE_2
 
     HOST_NAME=`/bin/hostname`
 
@@ -151,15 +152,27 @@ mm_url_confro_get() {
     /bin/rm -f "${LOCAL_FILE}"
     ( /usr/bin/test "${LOCAL_FILE}" = "/etc/minimyth.d/minimyth.conf" \
           && mm_url_get "${MM_TFTP_BOOT_URL}${REMOTE_FILE_0}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file downloaded from ${MM_TFTP_BOOT_URL}${REMOTE_FILE_0}'" \
+                   || /bin/true \
+             ) \
     ) || \
     ( /usr/bin/test -n "${REMOTE_FILE_0}" \
           && mm_url_get "${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file downloaded from ${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}'" \
+                   || /bin/true \
+             ) \
     ) || \
     ( /usr/bin/test -n "${REMOTE_FILE_1}" \
           && mm_url_get "${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_1}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file downloaded from ${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_1}'" \
+                   || /bin/true \
+             ) \
     ) || \
     ( /usr/bin/test -n "${REMOTE_FILE_2}" \
           && cp "${REMOTE_FILE_2}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file copied from ${REMOTE_FILE_2}'" \
+                   || /bin/true \
+             ) \
     ) || \
     return
 
@@ -172,6 +185,7 @@ mm_url_confrw_get() {
 
     local HOST_NAME
     local REMOTE_FILE_0
+    local REMOTE_FILE_1
 
     HOST_NAME=`/bin/hostname`
 
@@ -182,10 +196,20 @@ mm_url_confrw_get() {
         REMOTE_FILE_0=`/bin/echo ${REMOTE_FILE}`
         REMOTE_FILE_0="conf-rw/${HOST_NAME}/${REMOTE_FILE_0}"
     fi
+    /usr/bin/test -e "/media/boot" && REMOTE_FILE_1="/media/boot/${REMOTE_FILE}"
 
     /bin/rm -f "${LOCAL_FILE}"
     ( /usr/bin/test -n "${REMOTE_FILE_0}" \
           && mm_url_get "${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file downloaded from ${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}'" \
+                   || /bin/true \
+             ) \
+    ) || \
+    ( /usr/bin/test -n "${REMOTE_FILE_1}" \
+          && cp "${REMOTE_FILE_1}" "${LOCAL_FILE}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file copied from ${REMOTE_FILE_1}'" \
+                   || /bin/true \
+             ) \
     ) || \
     return
 
@@ -414,6 +438,7 @@ mm_url_confrw_put() {
 
     local HOST_NAME
     local REMOTE_FILE_0
+    local REMOTE_FILE_1
 
     HOST_NAME=`/bin/hostname`
 
@@ -437,10 +462,17 @@ mm_url_confrw_put() {
         REMOTE_FILE_0=`/bin/echo ${REMOTE_FILE}`
         REMOTE_FILE_0="conf-rw/${HOST_NAME}/${REMOTE_FILE_0}"
     fi
+    /usr/bin/test -e "/media/boot" && REMOTE_FILE_1="/media/boot/${REMOTE_FILE}"
 
     ( /usr/bin/test -n "${REMOTE_FILE_0}" \
           && mm_url_put "${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}" "${LOCAL_FILE}" \
-          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}' uploaded." \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file uploaded as ${MM_MINIMYTH_BOOT_URL}${REMOTE_FILE_0}'" \
+                   || /bin/true \
+             ) \
+    ) || \
+    ( /usr/bin/test -n "${REMOTE_FILE_0}" \
+          && cp "${LOCAL_FILE}" "${REMOTE_FILE_1}" \
+          && ( /usr/bin/logger -s -t minimyth -p "local0.info" "'${LOCAL_FILE} file saved as ${REMOTE_FILE_1}'" \
                    || /bin/true \
              ) \
     ) || \
@@ -973,8 +1005,58 @@ mm_cookiejar_save() {
         fi
     fi
 
-    /usr/bin/logger -s -t minimyth -p "local0.error" \
+    /usr/bin/logger -s -t minimyth -p "local0.info" \
         "[functions/mm_cookiejar_save] MythBrowser cookiejar.txt file and Chrome/Mozilla configs uploaded sucessfuly..."
+    /bin/true
+    return
+}
+
+mm_bt_state_save() {
+
+    if [ -d /var/lib/bluetooth ] ; then
+        cd /var/lib
+        tar -jcvvf /tmp/bt-state.tar.bz2 ./blue*
+        mm_confrw_put "bt-state.tar.bz2" "/tmp/bt-state.tar.bz2"
+        if [ $? -ne 0 ] ; then
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
+                "[functions/mm_bt_state_save] failed to save the bt-state.tar.bz2 file ..."
+            /bin/false
+            return
+        fi
+    fi
+    rm -f /tmp/bt-state.tar.bz2
+
+    /usr/bin/logger -s -t minimyth -p "local0.info" \
+        "[functions/mm_bt_state_save] Bluetooth state uploaded sucessfuly..."
+    /bin/true
+    return
+}
+
+mm_bt_switch_audio_to_default() {
+
+    if [ x$(readlink /etc/asound.conf) = "x/etc/asound-bt.conf" ] ; then
+        if [ -e /etc/asound-hdmi.conf ] ; then
+            ln -sf /etc/asound-hdmi.conf /etc/asound.conf
+        fi
+    fi
+    return 0
+}
+
+mm_bt_state_restore() {
+
+    mm_confrw_get "bt-state.tar.bz2" "/tmp/bt-state.tar.bz2"
+    if [ $? -ne 0 ] ; then
+        /usr/bin/logger -s -t minimyth -p "local0.error" \
+            "[functions/mm_bt_state_restore] failed to restore the bt-state.tar.bz2 file ..."
+        /bin/false
+        return
+    fi
+    rm -rf /var/lib/blue*
+    bunzip2 -dc /tmp/bt-state.tar.bz2 | tar -xf - -C /var/lib
+    rm -f /tmp/bt-state.tar.bz2
+
+    /usr/bin/logger -s -t minimyth -p "local0.info" \
+        "[functions/mm_bt_state_restore] Bluetooth state restored sucessfuly..."
     /bin/true
     return
 }
