Adding Netflix support

diff --git a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
--- a/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
+++ b/script/meta/minimyth/files/source/rootfs/etc/rc.d/functions
@@ -912,22 +912,36 @@ mm_themecache_save() {
 
 mm_cookiejar_save() {
 
-    if /usr/bin/test ! -e /home/minimyth/.mythtv/MythBrowser/cookiejar.txt ; then
-        /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_cookiejar_save] failed to save the MythBrowser cookiejar.txt file as file not exists..."
-        /bin/false
-        return
+    if /usr/bin/test -e /home/minimyth/.mythtv/MythBrowser/cookiejar.txt ; then
+        mm_confrw_put "mythbrowser_cookiejar.txt" "/home/minimyth/.mythtv/MythBrowser/cookiejar.txt"
+        if /usr/bin/test $? -ne 0 ; then
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
+                "[functions/mm_cookiejar_save] failed to upload the MythBrowser cookiejar.txt file!"
+            /bin/false
+            return
+        fi
     fi
 
-    mm_confrw_put "mythbrowser_cookiejar.txt" "/home/minimyth/.mythtv/MythBrowser/cookiejar.txt"
-    if /usr/bin/test $? -ne 0 ; then
-        /usr/bin/logger -s -t minimyth -p "local0.error" \
-            "[functions/mm_cookiejar_save] failed to upload the MythBrowser cookiejar.txt file!"
-        /bin/false
-        return
+    if /usr/bin/test -d /home/minimyth/.config ; then
+        cd /home/minimyth
+        tar -jcvvf /tmp/google-chrome-config.tar.bz2 ./.config*
+        mm_confrw_put "google-chrome-config.tar.bz2" "/tmp/google-chrome-config.tar.bz2"
+        rm -f /tmp/google-chrome-config.tar.bz2
+        if /usr/bin/test $? -ne 0 ; then
+            /usr/bin/logger -s -t minimyth -p "local0.error" \
+                "[functions/mm_cookiejar_save] failed to upload the /google-chrome-config.tar.bz2 file!"
+            /bin/false
+            return
+        else
+            /bin/true
+            return
+        fi
     fi
 
-    /bin/true
+    /usr/bin/logger -s -t minimyth -p "local0.error" \
+        "[functions/mm_cookiejar_save] MythBrowser cookiejar.txt file and /home/minimyth/.config directory are not existsing..."
+    /bin/false
+    return
 }
 
 mm_message_output() {
